Contacts.Web/Models/CreateContactViewModel.cs
namespace Contacts.Web.Models;

public class CreateContactViewModel
{
    public string Name { get; set; } = string.Empty;
    public string MobilePhone { get; set; } = string.Empty;
    public string JobTitle { get; set; } = string.Empty;
    public string BirthDate { get; set; } = string.Empty;
}

Contacts.Web/Models/UpdateContactViewModel.cs
namespace Contacts.Web.Models;

public class UpdateContactViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string MobilePhone { get; set; } = string.Empty;
    public string JobTitle { get; set; } = string.Empty;
    public string BirthDate { get; set; } = string.Empty;
}

Contacts.Web/Components/ContactsListViewComponent.cs
using Contacts.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Contacts.Web.Components;

public class ContactsListViewComponent : ViewComponent
{
    private readonly IContactService _contactService;
    public ContactsListViewComponent(IContactService contactService)
    {
        _contactService = contactService;
    }
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var contacts = await _contactService.GetAllAsync();
        return View(contacts);
    }
}

Contacts.Web/Controllers/ContactController.cs
using Contacts.Application.Services.Interfaces;
using Contacts.Web.Extentions;
using Contacts.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Contacts.Web.Controllers
{
    public class ContactController : Controller
    {

        private readonly IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        public async Task<ActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddContact(CreateContactViewModel model)
        {
            var createdContact = await _contactService.CreateContactAsync(model.ToCreateContactDto());
            return Ok(createdContact);
        }

        [HttpPut]
        public async Task<ActionResult> UpdateContact(UpdateContactViewModel model)
        {
            var updatedContact = await _contactService.UpdateContactAsync(model.ToContactDto());
            return Ok(updatedContact);
        }

        [HttpDelete]
        public async Task<ActionResult> DeleteContact(int id)
        {
            await _contactService.DeleteContactAsync(id);
            return NoContent();
        }

        [HttpGet]
        public async Task<ActionResult> GetContactById(int id)
        {
            var contact = await _contactService.GetContactByIdAsync(id);
            return Ok(contact);
        }
    }
}

Contacts.Web/Views/Contact/Index.cshtml
@{
}
@await Component.InvokeAsync("ContactsList")

<button type="button" class="btn btn-primary" id="openModal" data-bs-toggle="modal" data-bs-target="#popUp">
    Добавить запись
</button>

<div class="modal fade" id="popUp" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Форма</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="form-floating" id="creatingForm">
                    <input type="text" class="d-none" id="contactId" name="Id" />
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="Name" name="Name">
                        <label for="Name">Имя</label>
                        <div class="text-danger text-center" align-content-center" id="nameError"></div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="MobilePhone" name="MobilePhone">
                        <label for="MobilePhone">Номер телефона</label>
                        <div class="text-danger text-center" id="MobilePhoneError"></div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="JobTitle" name="JobTitle">
                        <label for="JobTitle">Должность</label>
                        <div class="text-danger text-center" id="JobTitleError"></div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="date" class="form-control" id="BirthDate" name="BirthDate">
                        <label for="BirthDate">Дата рождения</label>
                        <div class="text-danger text-center" id="BirthDateError"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" id="closeButton" data-bs-dismiss="modal">Закрыть</button>
                        <a class="btn btn-danger" asp-action="DeleteContact" id="deleteContact">Удалить</a>
                        <button type="submit" class="btn btn-primary" id="addContact">Добавить запись</button>
                        <button type="submit" class="btn btn-primary d-none" id="updateContact">Обновить данные</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Contacts.Web/Views/Shared/Components/ContactsList/Default.cshtml
@model IList<Contacts.Application.DTO.Contacts.ContactDto>
@{
}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя</th>
            <th scope="col">Место работы</th>
            <th scope="col">Номер телефона</th>
            <th scope="col">День рождения</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var contact in Model)
        {
            <tr class="table-row" data-bs-toggle="modal" data-bs-target="#popUp" data-id="@contact.Id" data-name="@contact.Name" data-jobTitle = "@contact.JobTitle" data-mobilePhone="@contact.MobilePhone" data-birthDate="@contact.BirthDate"> 
                <th scope="row">@contact.Id</th>
                <td>@contact.Name</td>
                <td>@contact.JobTitle</td>
                <td>@contact.MobilePhone</td>
                <td>@contact.BirthDate.Split(' ')[0]</td>
            </tr>
        }
    </tbody>

</table>

Contacts.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Список контактов</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Contacts.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Contact" asp-action="Index">Список контактов</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/validation.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/modal.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>